export const SET_FROM = 'SET_FROM';
export const SET_TO = 'SET_TO';
export const SET_CURRENT_SELECTING_LEFT_CITY =
  'SET_CURRENT_SELECTING_LEFT_CITY';
export const SET_DEPART_DATE = 'SET_DEPART_DATE';
export const SET_HIGHSPEED = 'SET_HIGHSPEED';
