export const SET_CITY_DATA = 'SET_CITY_DATA';
export const SET_IS_LOADING_CITY_DATA = 'SET_IS_LOADING_CITY_DATA';
export const SET_SEARCH_KEYWORD = 'SET_SEARCH_KEYWORD'
export const SET_SEARCH_CITY_DATA = 'SET_SEARCH_CITY_DATA'
